const emojis = {
    "Croatia": "🇭🇷",
    "France": "🇫🇷",
    "Belgium": "🇧🇪",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿",
    "Russia": "🇷🇺",
    "Sweden": "🇸🇪",
    "Brazil": "🇧🇷",
    "Uruguay": "🇺🇾",
    "Colombia": "🇨🇴",
    "Switzerland": "🇨🇭",
    "Japan": "🇯🇵",
    "Mexico": "🇲🇽",
    "Denmark": "🇩🇰",
    "Spain": "🇪🇸",
    "Portugal": "🇵🇹",
    "Argentina": "🇦🇷",
    "Panama": "🇵🇦",
    "Tunisia": "🇹🇳",
    "Poland": "🇵🇱",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Costa Rica": "🇨🇷",
    "Germany": "🇩🇪",
    "Korea Republic": "🇰🇷",
    "Nigeria": "🇳🇬",
    "Iceland": "🇮🇸",
    "Peru": "🇵🇪",
    "Australia": "🇦🇺",
    "Morocco": "🇲🇦",
    "Iran": "🇮🇷",
    "Egypt": "🇪🇬",
    "Saudi Arabia": "🇸🇦",
    // Italy, Republic of Ireland, Hungary, Slovakia, Northern Ireland, Austria, Czech Republic, Turkey, Ukraine, Romania, Albania
    "Italy": "🇮🇹",
    "Republic of Ireland": "🇮🇪",
    "Hungary": "🇭🇺",
    "Slovakia": "🇸🇰",
    "Northern Ireland": "🇬🇧",
    "Austria": "🇦🇹",
    "Czech Republic": "🇨🇿",
    "Turkey": "🇹🇷",
    "Ukraine": "🇺🇦",
    "Romania": "🇷🇴",
    "Albania": "🇦🇱",
    "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿󠁧󠁢󠁷󠁬󠁳󠁿",
}

export default emojis;